services:
  knight-wallet:
    container_name: knight-wallet
    restart: always
    build:
      context: .
    ports:
      - "3333:3333"
    env_file:
      - .env
    environment:
      - NODE_ENV=production